*** SLURM BATCH JOB 'diffusion' STARTING ***
*** Activating environment 236004_transformers_project ***
CUDA flag: True
Device: cuda
All logs will be located in: logs
This experiment's logs will be located in: logs/logs/-date=2025_06_13_19:00:38
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Traceback (most recent call last):
  File "/home/amit.vaisman/236004_transformers_project/subnet_train.py", line 242, in <module>
    main()
  File "/home/amit.vaisman/236004_transformers_project/subnet_train.py", line 190, in main
    accelerator.init_trackers(
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/accelerate/accelerator.py", line 629, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/accelerate/accelerator.py", line 2393, in init_trackers
    self.trackers.append(tracker_init(project_name, **init_kwargs.get(str(tracker), {})))
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/accelerate/tracking.py", line 81, in execute_on_main_process
    return function(self, *args, **kwargs)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/accelerate/tracking.py", line 298, in __init__
    self.run = wandb.init(project=self.run_name, **kwargs)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1691, in init
    wandb._sentry.reraise(e)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 156, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1623, in init
    wi.maybe_login(init_settings)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 208, in maybe_login
    wandb_login._login(
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 314, in _login
    key, key_status = wlogin.prompt_api_key(referrer=referrer)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 242, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Traceback (most recent call last):
  File "/home/amit.vaisman/236004_transformers_project/subnet_train.py", line 242, in <module>
    main()
  File "/home/amit.vaisman/236004_transformers_project/subnet_train.py", line 190, in main
    accelerator.init_trackers(
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/accelerate/accelerator.py", line 629, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/accelerate/accelerator.py", line 2393, in init_trackers
    self.trackers.append(tracker_init(project_name, **init_kwargs.get(str(tracker), {})))
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/accelerate/tracking.py", line 81, in execute_on_main_process
    return function(self, *args, **kwargs)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/accelerate/tracking.py", line 298, in __init__
    self.run = wandb.init(project=self.run_name, **kwargs)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1691, in init
    wandb._sentry.reraise(e)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 156, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1623, in init
    wi.maybe_login(init_settings)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 208, in maybe_login
    wandb_login._login(
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 314, in _login
    key, key_status = wlogin.prompt_api_key(referrer=referrer)
  File "/home/amit.vaisman/miniconda3/envs/236004_transformers_project/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 242, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
*** SLURM BATCH JOB 'diffusion' DONE ***
